#!/bin/bash -x

__deploy=( bash editrc git inputrc python ruby tmux vim conda )

if [ -e ~/.not_a_server ]; then
  __deploy+=( ag i3 tridactyl kitty Xresources )
  __dot_config_deploy=( rofi clipster )
else
  echo "Only installing for a server; otherwise, please touch .not_a_server in your home directory."
fi

mkdir -p ~/.vim
cd ~/.vim
[ -d ftdetect ] || ln -s ~/dotfiles/ftdetect ftdetect
[ -d ftplugin ] || ln -s ~/dotfiles/ftplugin ftplugin
[ -d syntax   ] || ln -s ~/dotfiles/syntax syntax

mkdir -p ~/.config
ln -s ~/.vim ~/.config/nvim
cd ~/.config/nvim
[ -e init.vim ] || ln -s ~/dotfiles/nvim/nvimrc init.vim

cd ~
[ -L ~/bin ] && rm ~/bin
ln -s ~/dotfiles/bin bin
[ -f ~/.profile ] || ln -s ~/.bashrc .profile

for dir in "${__deploy[@]}"; do
  for path in ~/dotfiles/"${dir}"/*; do
    file_name=`basename "${path}"`
    [ -L ."${file_name}" ] && rm ."${file_name}"
    ln -s "${path}" ."${file_name}"
  done
done

cd ~/.config

for dir in "${__dot_config_deploy[@]}"; do
  for path in ~/dotfiles/"${dir}"/*; do
    file_name=${dir}/`basename "${path}"`
    mkdir -p "${dir}"
    [ -L "${file_name}" ] && rm "${file_name}"
    ln -s "${path}" "${file_name}"
  done
done
