#!/bin/bash -x

cd ~
LIST=( agignore bashrc gitconfig i3 i3status.conf inputrc pythonrc.py tmux.conf vimrc vimrc.bundles )
for x in "${LIST[@]}"; do
  ln -s ~/dotfiles/"$x" ."$x"
done
ln -s .vimrc .nvimrc
ln -s .vimrc.bundles .nvimrc.bundles

mkdir -p ~/bin
cd ~/bin
for x in `ls ~/dotfiles/bin`; do
  ln -s ~/dotfiles/bin/"$x" "$x"
done
