" vim: sw=2 ts=2 sts=2 expandtab ft=vim
source ~/.vimrc
nmap ,<C-T> :terminal bash --rcfile ~/dotfiles/bash/bashrc_neovim<CR>
"tnoremap <C-\> <C-\><C-N>
tnoremap <Leader><Esc> <C-\><C-N>

" Stupid nonsense trying to open current terminal line in split, I seriously cannot believe how dumb this is
"tnoremap <C-J> <C-\><C-N>G?.<CR>v?^\$<CR>lly:new<CR>:setl buftype=nofile<CR>:nnoremap <buffer> <lt>C-J> ggIa<lt>Esc>vG$y:bw<lt>CR>i<lt>Esc>dd<lt>C-\><lt>C-N>pi<CR>:inoremap <buffer> <lt>C-J> <lt>Esc>ggIa<lt>Esc>vG$y:bw<lt>CR>i<lt>Esc>dd<lt>C-\><lt>C-N>pi<CR>p
