[ids]

*

[main]

capslock = overloadt2(control, esc, 200)

control = overloadt2(control, esc, 200)

alt = altgr

[altgr]

h = left
j = down
k = up
l = right

u = home
i = pageup
o = pagedown
p = end
